import type { Metadata } from "next";
// Fonts
import { Cairo } from "next/font/google";
// Components
import Navbar from "@/components/Navbar";
import Header from "@/components/Header";

export const metadata: Metadata = {
    title: "لوحة التحكم",
    description: "Generated by Abdullah Hasson",
};

const cairo = Cairo({
    variable: "--font-cairo",
    subsets: ["arabic"],
})
  

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={`dashboard flex flex-col bg-bgmain w-full h-screen flex-1 ${cairo.variable}`}>
            <Header />

            <div className="flex max-[768px]:flex-col-reverse h-[calc(100vh-80px)] max-[768px]:h-screen w-full">
                <Navbar />

                <div className="flex flex-col flex-[5] gap-5 max-[768px]:flex-[12] p-5">
                    {children}
                </div>
            </div>
        </div>
    );
}
