// Meta
import type { Metadata } from "next";


export const metadata: Metadata = {
    title: "لوحة التحكم | جداول التمارين",
    description: "Generated by Abdullah Hasson",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            {children}
        </>
    );
}
